language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t detleffolke/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true detleffolke/docker-react npm run test

